presubmits:
  cert-manager/csi-lib:

  - name: pull-cert-manager-csi-lib-verify
    always_run: true
    max_concurrency: 8
    decorate: true
    branches:
    - main
    labels:
    spec:
      containers:
      - image: golang:1.20
        args:
        - ./hack/verify-all.sh
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-csi-lib-e2e
    decorate: true
    # TODO: Keep optional to not block other PRs. Change once e2e test
    # boilerplate code has been merged to main.
    always_run: false
    optional: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/nix-dind:20240418-1d150aa-2.11.0
        args:
        - runner
        - nix
        - flake
        - check
        - -L
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

