presets:

- labels:
    preset-deployer-github-token: "true"
  env:
  - name: GITHUB_USER
    value: jetstack-bot
  - name: GITHUB_TOKEN_FILE
    value: /etc/github/token
  volumeMounts:
  - name: github-token
    mountPath: /etc/github
  volumes:
  - name: github-token
    secret:
      secretName: bot-github-token

- labels:
    preset-deployer-ssh-key: "true"
  volumeMounts:
  - name: ssh
    mountPath: /root/.ssh
  volumes:
  - name: ssh
    secret:
      secretName: jetstack-bot-ssh-keys
      defaultMode: 0400

- labels:
    preset-deployer-service-account: "true"
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /creds/service-account.json
  volumeMounts:
    - name: creds
      mountPath: /creds
  volumes:
  - name: creds
    secret:
      secretName: deployer-service-account
