presets:

# The "deployer" github account is https://github.com/cert-manager-bot.
# The credentials for this account can be found in the 1Password vault.
# Long-term, we probably want to use a GitHub App here too instea of this
# bot account.

- labels:
    preset-deployer-github-token: "true"
  env:
  - name: GITHUB_USER
    value: cert-manager-bot
  - name: GITHUB_TOKEN_FILE
    value: /etc/github/token
  volumeMounts:
  - name: github-token
    mountPath: /etc/github
  volumes:
  - name: github-token
    secret:
      secretName: cert-manager-bot-github-token

- labels:
    preset-deployer-ssh-key: "true"
  volumeMounts:
  - name: ssh
    mountPath: /root/.ssh
  volumes:
  - name: ssh
    secret:
      secretName: cert-manager-bot-ssh-keys
      defaultMode: 0400

- labels:
    preset-deployer-service-account: "true"
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /creds/service-account.json
  volumeMounts:
    - name: creds
      mountPath: /creds
  volumes:
  - name: creds
    secret:
      secretName: cert-manager-bot-gcp-service-account
