presubmits:
  cert-manager/istio-csr:

  - name: pull-cert-manager-istio-csr-verify
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-unit
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-unit
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-test-ecc
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-ecc
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-ca-rotation
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-carotation
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-pure-runtime-config
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e-pure-runtime
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4


  - name: pull-cert-manager-istio-csr-istio-v1-17
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: ISTIO_VERSION
          value: "1.17.8"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-istio-v1-18
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: ISTIO_VERSION
          value: "1.18.7"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-istio-v1-19
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: ISTIO_VERSION
          value: "1.19.9"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-istio-v1-20
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: ISTIO_VERSION
          value: "1.20.8"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-istio-v1-21
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: ISTIO_VERSION
          value: "1.21.4"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-istio-v1-22
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: ISTIO_VERSION
          value: "1.22.2"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4

  - name: pull-cert-manager-istio-csr-istio-v1-23
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240422-6b43e85-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: ISTIO_VERSION
          value: "1.23.0"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
