presubmits:
  cert-manager/istio-csr:

  - name: pull-cert-manager-istio-csr-verify
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240108-30ad0a8-bookworm
        args:
        - runner
        - make
        - vendor-go
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-istio-csr-unit
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240108-30ad0a8-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-unit
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-istio-csr-ca-rotation
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240108-30ad0a8-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-carotation
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.14
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-14
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240108-30ad0a8-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.14.6"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.15
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-15
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240108-30ad0a8-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.15.5"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.16
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-16
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240108-30ad0a8-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.16.2"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.17
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-17
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240108-30ad0a8-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.17.2"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"
