presubmits:
  cert-manager/approver-policy:

  - name: pull-cert-manager-approver-policy-verify
    decorate: true
    always_run: true
    max_concurrency: 8
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240104-602a628-bookworm
        args:
        - runner
        - make
        - vendor-go
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-approver-policy-test
    decorate: true
    always_run: true
    max_concurrency: 8
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240104-602a628-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-unit
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-approver-policy-smoke
    decorate: true
    always_run: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20240104-602a628-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-smoke
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"
