apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tide
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
