apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crier-get-pods
  namespace: test-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-test-pods
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: crierclient
