apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tide-gcp-admin-binding
  namespace: test-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tide
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: client
