apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sinker
  namespace: test-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sinker
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: client
