apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-test-pods
  namespace: test-pods
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list