apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: prow
  annotations:
    iam.gke.io/gcp-service-account: testgrid-updater@cert-manager-tests-trusted.iam.gserviceaccount.com
  name: testgrid-updater
  namespace: test-pods
