presubmits:
  cert-manager/cert-manager:
    # Why do we have only have presubmits on "master" but not on the
    # to-be-released branch, e.g. "release-1.9"? Because we don't need to be
    # testing e.g. release-1.9 before we have made the first alpha release, e.g.,
    # "1.9.0-alpha.0". See Step 13.3 in
    # https://cert-manager.io/docs/contributing/release-process/
    - agent: kubernetes
      always_run: true
      annotations:
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      decorate: true
      description: Runs unit and integration tests and verification scripts
      labels:
        preset-make-volumes: "true"
        preset-service-account: "true"
      max_concurrency: 8
      name: pull-cert-manager-make-test
      optional: false
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - ci-presubmit
              - test-ci
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 2
                memory: 4Gi
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    # Helm chart verification currently requires Docker.
    # We maintain a standalone presubmit for running this.
    # See https://github.com/helm/chart-testing/issues/53
    # Explicitly calls vendor-go because of this gotcha: https://github.com/cert-manager/cert-manager/blob/066fcbbbfa0e9840632a5dc3a5c36f6261c53405/make/tools.mk#L423-L426
    - agent: kubernetes
      always_run: true
      annotations:
        description: Verifies the Helm chart passes linting checks
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      decorate: true
      labels:
        preset-dind-enabled: "true"
        preset-make-volumes: "true"
        preset-service-account: "true"
      max_concurrency: 8
      name: pull-cert-manager-chart
      spec:
        containers:
          - args:
              - runner
              - make
              - vendor-go
              - verify-chart
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 1
                memory: 1Gi
            # docker-in-docker needs privileged mode
            securityContext:
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    - agent: kubernetes
      always_run: false
      annotations:
        description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      decorate: true
      labels:
        preset-cloudflare-credentials: "true"
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-enable-all-feature-gates-disable-ssa: "true"
        preset-ginkgo-skip-default: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
      max_concurrency: 4
      name: pull-cert-manager-e2e-v1-20
      optional: true
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.20
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    - agent: kubernetes
      always_run: false
      annotations:
        description: Runs the end-to-end test suite against a Kubernetes v1.21 cluster
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      decorate: true
      labels:
        preset-cloudflare-credentials: "true"
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-enable-all-feature-gates-disable-ssa: "true"
        preset-ginkgo-skip-default: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
      max_concurrency: 4
      name: pull-cert-manager-e2e-v1-21
      optional: true
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.21
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    - agent: kubernetes
      always_run: false
      annotations:
        description: Runs the end-to-end test suite against a Kubernetes v1.22 cluster
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      decorate: true
      labels:
        preset-cloudflare-credentials: "true"
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-enable-all-feature-gates: "true"
        preset-ginkgo-skip-default: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
      max_concurrency: 4
      name: pull-cert-manager-e2e-v1-22
      optional: true
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.22
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    - agent: kubernetes
      always_run: false
      annotations:
        description: Runs the end-to-end test suite against a Kubernetes v1.23 cluster
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      decorate: true
      labels:
        preset-cloudflare-credentials: "true"
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-enable-all-feature-gates: "true"
        preset-ginkgo-skip-default: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
      max_concurrency: 4
      name: pull-cert-manager-e2e-v1-23
      optional: true
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.23
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    # This is the default e2e test for all PRs against cert-manager master branch
    - agent: kubernetes
      always_run: true
      annotations:
        description: Runs 'make e2e-ci K8S_VERSION=1.24'
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      decorate: true
      labels:
        preset-cloudflare-credentials: "true"
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-enable-all-feature-gates: "true"
        preset-ginkgo-skip-default: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
      max_concurrency: 4
      name: pull-cert-manager-e2e-v1-24
      optional: false
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.24
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    # Verifies upgrade from the latest published release with both Helm chart and static manifests.
    # Explicitly calls vendor-go because of this gotcha: https://github.com/cert-manager/cert-manager/blob/066fcbbbfa0e9840632a5dc3a5c36f6261c53405/make/tools.mk#L423-L426
    - # This job will run on Kubernetes cluster.
      agent: kubernetes
      # Run always
      always_run: true
      annotations:
        description: Runs cert-manager upgrade from latest published release
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches:
        - master
      # Pod utilities will be set up.
      decorate: true
      labels:
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-make-volumes: "true"
        preset-service-account: "true"
      # No more than 4 instances of this job at the same time.
      max_concurrency: 4
      name: pull-cert-manager-upgrade
      optional: false
      spec:
        containers:
          - args:
              - runner
              - make
              - K8S_VERSION=1.24
              - vendor-go
              - test-upgrade
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    # An E2E test job to allow us to manually trigger the Venafi  TPP E2E tests
    # with the following GitHub comment:
    #
    #  /test pull-cert-manager-issuers-venafi-tpp
    #
    # See https://github.com/cert-manager/cert-manager/issues/3555
    #
    - agent: kubernetes
      always_run: false
      annotations:
        description: Runs the E2E tests with 'Venafi TPP' in name
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches: []
      decorate: true
      labels:
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-ginkgo-focus-venafi-tpp: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
        preset-venafi-tpp-credentials: "true"
      max_concurrency: 4
      name: pull-cert-manager-issuers-venafi-tpp
      optional: true
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.24
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    # An E2E test job to allow us to manually trigger the Venafi Cloud E2E tests
    # with the following GitHub comment:
    #
    #  /test pull-cert-manager-issuers-venafi-cloud
    #
    # The regular presubmit jobs do not run Venafi e2e tests.
    #
    - agent: kubernetes
      always_run: false
      annotations:
        description: Runs the E2E tests with 'Venafi Cloud' in name
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches: []
      decorate: true
      labels:
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-ginkgo-focus-venafi-cloud: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
        preset-venafi-cloud-credentials: "true"
      max_concurrency: 4
      name: pull-cert-manager-e2e-issuers-venafi-cloud
      optional: true
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.23
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
    - agent: kubernetes
      always_run: false
      annotations:
        description: Runs the E2E tests with all feature gates disabled
        testgrid-create-test-group: "true"
        testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      branches: []
      decorate: true
      labels:
        preset-cloudflare-credentials: "true"
        preset-default-e2e-volumes: "true"
        preset-dind-enabled: "true"
        preset-disable-all-alpha-beta-feature-gates: "true"
        preset-ginkgo-skip-default: "true"
        preset-make-volumes: "true"
        preset-retry-flakey-tests: "true"
        preset-service-account: "true"
      max_concurrency: 4
      name: pull-cert-manager-e2e-feature-gates-disabled
      optional: true
      spec:
        containers:
          - args:
              - runner
              - make
              - -j
              - vendor-go
              - e2e-ci
              - K8S_VERSION=1.23
            image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
            resources:
              requests:
                cpu: 3500m
                memory: 12Gi
            securityContext:
              capabilities:
                add:
                  - SYS_ADMIN
              privileged: true
        dnsConfig:
          options:
            - name: ndots
              value: "1"
