periodics:
  - agent: kubernetes
    annotations:
      description: Runs unit and integration tests and verification scripts
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-make-test
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - ci-presubmit
            - test-ci
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 2
              memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-enable-all-feature-gates-disable-ssa: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-v1-20
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.20
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.21 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-enable-all-feature-gates-disable-ssa: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-v1-21
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.21
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.22 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-enable-all-feature-gates: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-v1-22
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.22
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.23 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-enable-all-feature-gates: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-v1-23
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.23
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.24 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-enable-all-feature-gates: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-v1-24
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.24
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  # This test runs Venafi (VaaS and TPP) tests once every 12hrs.
  # This is the only CI test job that runs those.
  - agent: kubernetes
    annotations:
      description: Runs Venafi (VaaS and TPP) e2e tests against Kubernetes v1.24 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 12h
    labels:
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-ginkgo-focus-venafi: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
      preset-venafi-cloud-credentials: "true"
      preset-venafi-tpp-credentials: "true"
    name: ci-cert-manager-venafi
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.24
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs cert-manager upgrade test every 8 hours
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    # extra refs specify what repo should be cloned
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 8h
    labels:
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-upgrade
    spec:
      containers:
        - args:
            - runner
            - make
            - K8S_VERSION=1.24
            - vendor-go
            - test-upgrade
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  # TODO: find a permanent home for the AWS periodics and reinstate this job
  # - name: aws-tests
  #   interval: 48h
  #   agent: kubernetes
  #   decorate: true
  #   extra_refs:            # Periodic job doesn't clone any repo by default, needs to be added explicitly
  #     - org: cert-manager
  #       repo: test-infra
  #       base_ref: main
  #     - org: cert-manager
  #       repo: cert-manager
  #       base_ref: master
  #   annotations:
  #     testgrid-create-test-group: 'true'
  #     testgrid-dashboards: jetstack-cert-manager-master
  #     testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
  #     description: Runs the end-to-end test suite against a EKS cluster
  #   labels:
  #     preset-service-account: "true"
  #     preset-dind-enabled: "true"
  #     preset-bazel-remote-cache-enabled: "true"
  #     preset-bazel-scratch-dir: "true"
  #     preset-aws-credentials: "true"
  #     preset-ginkgo-focus-http01-ingress: "true"
  #   spec:
  #     containers:
  #     - image: eu.gcr.io/jetstack-build-infra-images/golang-aws@sha256:1f330e4c9552ca383d157067b73fb0e090b64b0777939fd59e58b60e06020d66
  #       args:
  #       - bash
  #       - -c
  #       - |
  #         set -euo && \
  #         ls && \
  #         pwd && \
  #         cd /home/prow/go/src/github.com/cert-manager/test-infra/aws && \
  #         terraform init && \
  #         trap 'terraform destroy -auto-approve' ERR && \
  #         terraform apply -auto-approve && \
  #         ls && \
  #         pwd && \
  #         cd /home && \
  #         ls && \
  #         cd /home/prow/go/src/github.com/cert-manager/cert-manager && \
  #         ./devel/run-e2e.sh --acme-server-url=https://acme-staging-v02.api.letsencrypt.org/directory --ingress-controller-domain=aws.e2e-tests.cert-manager.io --testing-acme-email=cert-manager-dev-alerts@googlegroups.com --kubernetes-config=/home/prow/go/src/github.com/cert-manager/test-infra/aws/kubeconfig_cert-manager-cluster || true && \
  #         cd /home/prow/go/src/github.com/cert-manager/test-infra/aws && \
  #         terraform destroy -auto-approve;
  #       resources:
  #         requests:
  #           cpu: 3500m
  #           memory: 12Gi
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster with all feature gates disabled
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 24h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-make-volumes: "true"
      preset-retry-flakey-tests: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-feature-gates-disabled-v1-20
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.20
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.21 cluster with all feature gates disabled
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 24h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-make-volumes: "true"
      preset-retry-flakey-tests: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-feature-gates-disabled-v1-21
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.21
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.22 cluster with all feature gates disabled
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 24h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-make-volumes: "true"
      preset-retry-flakey-tests: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-feature-gates-disabled-v1-22
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.22
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.23 cluster with all feature gates disabled
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 24h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-make-volumes: "true"
      preset-retry-flakey-tests: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-feature-gates-disabled-v1-23
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.23
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.24 cluster with all feature gates disabled
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 24h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-make-volumes: "true"
      preset-retry-flakey-tests: "true"
      preset-service-account: "true"
    name: ci-cert-manager-e2e-feature-gates-disabled-v1-24
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.24
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
