presubmits:
  cert-manager/webhook-example:

  - name: pull-cert-manager-webhook-example-verify
    always_run: true
    context: pull-cert-manager-webhook-example-verify
    max_concurrency: 8
    decorate: true
    branches:
    - master
    spec:
      containers:
      - image: golang:1.19-buster
        args:
        - make
        - test
        resources:
          requests:
            cpu: 2
            memory: 4Gi
