presubmits:
  cert-manager/webhook-example:

  - name: pull-cert-manager-webhook-example-verify
    always_run: true
    max_concurrency: 8
    decorate: true
    branches:
    - master
    spec:
      containers:
      - image: golang:1.20-buster
        args:
        - make
        - test
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
