apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherrypicker
  labels:
    app: prow
    component: cherrypicker
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prow
      component: cherrypicker
  template:
    metadata:
      labels:
        app: prow
        component: cherrypicker
    spec:
      containers:
      - name: cherrypicker
        image: gcr.io/k8s-prow/cherrypicker:v20220301-2a7bee07aa
        args:
        - --dry-run=false
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-token-path=/etc/github/oauth
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: oauth-token
      - name: tmp
        emptyDir: {}
