# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - jetstack/kube-lego
  - jetstack/test-infra
  - jetstack/navigator
  - jetstack/tarmak
  - jetstack/okta-kubectl-auth
  - jetstack/puppet-module-aws_ebs
  - jetstack/puppet-module-calico
  - jetstack/puppet-module-etcd
  - jetstack/puppet-module-kubernetes
  - jetstack/puppet-module-kubernetes_addons
  - jetstack/puppet-module-prometheus
  - jetstack/puppet-module-vault_client
  - jetstack/puppet-module-tarmak
  - jetstack/vault-helper
  - jetstack/vault-unsealer
  - jetstack/vault-plugin-auth-templated-aws
  only_org_members: true
- repos:
  - cert-manager/cert-manager
  - cert-manager/website
  - cert-manager/trust-manager
  only_org_members: true

blunderbuss:
  # Only request a review from 1 reviewer
  request_count: 1

external_plugins:
  jetstack:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypick
    events:
    - issue_comment
    - pull_request
  cert-manager:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypick
    events:
    - issue_comment
    - pull_request

repo_milestone:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones:
  # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
  cert-manager/cert-manager:
    # https://github.com/orgs/cert-manager/teams/milestone-maintainers
    maintainers_id: 2805308
    maintainers_team: milestone-maintainers
  cert-manager/website:
    # https://github.com/orgs/cert-manager/teams/milestone-maintainers
    maintainers_id: 2805308
    maintainers_team: milestone-maintainers
  cert-manager/trust-manager:
    # https://github.com/orgs/cert-manager/teams/milestone-maintainers
    maintainers_id: 2805308
    maintainers_team: milestone-maintainers

milestone_applier:
  cert-manager/cert-manager:
    master: v1.12
    release-1.11: v1.11
    release-1.10: v1.10
    release-1.9: v1.9
    release-1.8: v1.8
    release-1.7: v1.7
    release-1.6: v1.6
    release-1.5: v1.5
    release-1.4: v1.4
    release-1.3: v1.3
    release-1.2: v1.2
    release-1.1: v1.1
    release-1.0: v1.0
    release-0.16: v0.16
    release-0.15: v0.15
    release-0.14: v0.14
    release-0.13: v0.13
    release-0.12: v0.12
    release-0.11: v0.11
    release-0.10: v0.10
    release-0.9: v0.9
    release-0.8: v0.8
  jetstack/kube-oidc-proxy:
    master: v0.2
    release-0.1: v0.1
    release-0.2: v0.2

config_updater:
  maps:
    config/labels.yaml:
      name: label-config
    config/config.yaml:
      name: config
    config/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config

require_matching_label:
- missing_label: needs-kind
  org: cert-manager
  repo: cert-manager
  prs: true
  regexp: ^kind/

plugins:

  jetstack:
    plugins:
    - assign
    - blockade
    - cherry-pick-unapproved
    - golint
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - milestone
    - milestonestatus
    - milestoneapplier
    - override
    - require-matching-label
    - shrug
    - size
    - skip
    - trigger
    - wip
    - yuks

  cert-manager:
    plugins:
    - approve
    - assign
    - dco
    - golint
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - milestone
    - milestonestatus
    - milestoneapplier
    - override
    - owners-label
    - require-matching-label
    - size
    - skip
    - trigger
    - verify-owners
    - wip

  cert-manager/cert-manager:
    plugins:
    - release-note

  jetstack/tarmak:
    plugins:
    - approve
    - dco
    - owners-label
    - release-note
    - verify-owners

  jetstack/kube-oidc-proxy:
    plugins:
    - approve
    - dco
    - owners-label
    - release-note
    - verify-owners

  jetstack/preflight:
    plugins:
    - approve
    - dco
    - verify-owners

  jetstack/version-checker:
    plugins:
    - approve
    - dco
    - owners-label
    - release-note
    - verify-owners

  jetstack/testing:
    plugins:
    - approve
    - config-updater
    - dco
    - owners-label
    - verify-owners

  munnerz/venafi-cm-demo:
    plugins:
    - trigger
