presubmits:
  cert-manager/release:
  - name: pull-cert-manager-release-verify
    always_run: true
    max_concurrency: 8
    decorate: true
    annotations:
      testgrid-create-test-group: 'false'
    labels:
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20240418-1d150aa-1.22
        args:
        - runner
        - make
        - presubmit
        resources:
          requests:
            # 3500m was chosen because that allows us to fit two jobs onto one
            # n1-standard-8 node, taking into account the amount of CPU allocated
            # to the kubelet. https://github.com/cert-manager/testing/pull/510
            cpu: 3500m
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
