presubmits:
  cert-manager/release:
  - name: pull-cert-manager-release-verify
    always_run: true
    max_concurrency: 8
    decorate: true
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/make-dind:20230405-38c1b22-bullseye
        args:
        - runner
        - make
        - presubmit
        resources:
          requests:
            # 3500m was chosen because that allows us to fit two jobs onto one
            # n1-standard-8 node, taking into account the amount of CPU allocated
            # to the kubelet. https://github.com/jetstack/testing/pull/510
            cpu: 3500m
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
