name: nix-dind # Name of the image to be built

variants:
  "2.11.0":
    arguments:
      BASE_IMAGE: "europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240419-d5dce7d-bookworm"
      NIX_VERSION: "2.11.0"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${NIX_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${NIX_VERSION}
