name: golang-dind # Name of the image to be built

variants:
  "1.20":
    arguments:
      BASE_IMAGE: "eu.gcr.io/jetstack-build-infra-images/make-dind:20230330-83ce2fd-bullseye@sha256:c8b46f4d9bca8dd7be8a02b1557f1f247fb9ba518cd2dd71002f3a295296bae2"
      GO_VERSION: "1.20.2"
  "1.19":
    arguments:
      BASE_IMAGE: "eu.gcr.io/jetstack-build-infra-images/bazelbuild@sha256:6409016944bf6d601062062a91d283bea64834fa1f6074430d16007366a1f89c"
      GO_VERSION: "1.19.7"
  "1.18":
    arguments:
      BASE_IMAGE: "eu.gcr.io/jetstack-build-infra-images/bazelbuild@sha256:4757d0b78814ccc138561b9e2b57c3b84d2b339d2d3c5c796e5520f3cd298aa4"
      GO_VERSION: "1.18.3"
  "1.17":
    arguments:
      BASE_IMAGE: "eu.gcr.io/jetstack-build-infra-images/bazelbuild@sha256:4757d0b78814ccc138561b9e2b57c3b84d2b339d2d3c5c796e5520f3cd298aa4"
      GO_VERSION: "1.17.11"
  "1.16":
    arguments:
      BASE_IMAGE: "eu.gcr.io/jetstack-build-infra-images/bazelbuild@sha256:4757d0b78814ccc138561b9e2b57c3b84d2b339d2d3c5c796e5520f3cd298aa4"
      GO_VERSION: "1.16.15"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${GO_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${GO_VERSION}
