# We don't need periodically testing the release-next breanch (e.g., the
# "release-1.9" branch) until we release the first alpha (e.g.,
# "1.9.0-alpha.0"). Since we can't "deactivate" the release-next periodics jobs
# until we have an alpha (there is no "skip" field on the ProwJob object), we
# set an arbitrarily large interval of 6 month. See Step 13.3 in
# https://cert-manager.io/docs/contributing/release-process/

# Since we're in an alpha phase now, we'll enable these tests
periodics:
  - agent: kubernetes
    annotations:
      description: Runs unit and integration tests and verification scripts
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-next
    decorate: true
    extra_refs:
      - base_ref: release-1.9
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-next-make-test
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - ci-presubmit
            - test-ci
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 2
              memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-next
    decorate: true
    extra_refs:
      - base_ref: release-1.9
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-enable-all-feature-gates-disable-ssa: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-next-e2e-v1-20
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.20
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.21 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-next
    decorate: true
    extra_refs:
      - base_ref: release-1.9
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-enable-all-feature-gates-disable-ssa: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-next-e2e-v1-21
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.21
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.22 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-next
    decorate: true
    extra_refs:
      - base_ref: release-1.9
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-next-e2e-v1-22
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.22
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.23 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-next
    decorate: true
    extra_refs:
      - base_ref: release-1.9
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-next-e2e-v1-23
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.23
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs the end-to-end test suite against a Kubernetes v1.24 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-next
    decorate: true
    extra_refs:
      - base_ref: release-1.9
        org: cert-manager
        repo: cert-manager
    interval: 2h
    labels:
      preset-cloudflare-credentials: "true"
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-ginkgo-skip-default: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-next-e2e-v1-24
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.24
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs Venafi (VaaS and TPP) e2e tests against Kubernetes v1.24 cluster
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-next
    decorate: true
    extra_refs:
      - base_ref: master
        org: cert-manager
        repo: cert-manager
    interval: 12h
    labels:
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-ginkgo-focus-venafi: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
      preset-venafi-cloud-credentials: "true"
      preset-venafi-tpp-credentials: "true"
    name: ci-cert-manager-next-venafi
    spec:
      containers:
        - args:
            - runner
            - make
            - -j
            - vendor-go
            - e2e-ci
            - K8S_VERSION=1.24
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
  - agent: kubernetes
    annotations:
      description: Runs cert-manager upgrade test every 8 hours
      testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
      testgrid-create-test-group: "true"
      testgrid-dashboards: jetstack-cert-manager-master
    decorate: true
    # extra refs specify what repo should be cloned
    extra_refs:
      - base_ref: release-1.9
        org: cert-manager
        repo: cert-manager
    interval: 8h
    labels:
      preset-default-e2e-volumes: "true"
      preset-dind-enabled: "true"
      preset-make-volumes: "true"
      preset-service-account: "true"
    name: ci-cert-manager-next-upgrade
    spec:
      containers:
        - args:
            - runner
            - make
            - cluster
            - verify_upgrade
          image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
          resources:
            requests:
              cpu: 3500m
              memory: 12Gi
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
