apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: branchprotector
spec:
  schedule: "54 * * * *"  # Every hour at 54 minutes past the hour
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
          containers:
          - name: branchprotector
            image: gcr.io/k8s-prow/branchprotector:v20240415-7013691e3
            args:
            - --config-path=/etc/config/config.yaml
            - --job-config-path=/etc/job-config
            - --github-app-id=$(GITHUB_APP_ID)
            - --github-app-private-key-path=/etc/github/cert
            - --confirm
            - --github-endpoint=http://ghproxy
            - --github-endpoint=https://api.github.com
            env:
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-app-token
                  key: appid
            volumeMounts:
            - name: github-app-token
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: job-config
              mountPath: /etc/job-config
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: github-app-token
            secret:
              secretName: github-app-token
          - name: config
            configMap:
              name: config
          - name: job-config
            configMap:
              name: job-config
