apiVersion: apps/v1
kind: Deployment
metadata:
  name: triageparty
  namespace: triageparty
spec:
  selector:
    matchLabels:
      app: triageparty
  template:
    metadata:
      labels:
        app: triageparty
    spec:
      containers:
      - name: triageparty
        image: triageparty/triage-party:1.4.0
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: cert-manager-bot-triage-party-github-token
              key: token
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /s/daily
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /s/daily
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 600
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: triageparty-config
