presets:
- labels:
    preset-cloudflare-credentials: "true"
  env:
  - name: CLOUDFLARE_E2E_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: api-token
  - name: CLOUDFLARE_E2E_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: email
  - name: CLOUDFLARE_E2E_DOMAIN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: domain

# The Venafi TPP test server is currently offline.
# Commenting out these pod presets when will cause the Venafi Issuer E2E tests
# to be skipped.
#
# - labels:
#     preset-venafi-tpp-credentials: "true"
#   env:
#   - name: VENAFI_TPP_URL
#     valueFrom:
#       secretKeyRef:
#         name: venafi-tpp
#         key: url
#   - name: VENAFI_TPP_ZONE
#     valueFrom:
#       secretKeyRef:
#         name: venafi-tpp
#         key: zone
#   - name: VENAFI_TPP_USERNAME
#     valueFrom:
#       secretKeyRef:
#         name: venafi-tpp
#         key: username
#   - name: VENAFI_TPP_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: venafi-tpp
#         key: password

- labels:
    preset-venafi-cloud-credentials: "true"
  env:
  - name: VENAFI_CLOUD_ZONE
    valueFrom:
      secretKeyRef:
        name: venafi-cloud
        key: zone
  - name: VENAFI_CLOUD_APITOKEN
    valueFrom:
      secretKeyRef:
        name: venafi-cloud
        key: apitoken

- labels:
    preset-retry-flakey-tests: "true"
  env:
  - name: FLAKE_ATTEMPTS
    value: "2"

presubmits:
  jetstack/cert-manager:

  - name: pull-cert-manager-bazel
    always_run: true
    cluster: gke
    context: pull-cert-manager-bazel
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs 'bazel test //...'
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - bazel
        - test
        - //...
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-bazel-experimental
    always_run: false
    optional: true
    cluster: gke
    context: pull-cert-manager-bazel-experimental
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs 'bazel test //...' using the 'experimental' Bazel version
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-experimental
        args:
        - runner
        - bazel
        - test
        - //...
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # Helm chart verification currently requires Docker.
  # We maintain a standalone presubmit for running this.
  # See https://github.com/helm/chart-testing/issues/53
  - name: pull-cert-manager-chart
    always_run: true
    cluster: gke
    context: pull-cert-manager-chart
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Verifies the Helm chart passes linting checks
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - make
        - verify_chart
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-deps
    always_run: true
    cluster: gke
    context: pull-cert-manager-deps
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Verifies dependency related files are up to date
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - make
        - verify_deps
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based cert-manager e2e job
  - name: pull-cert-manager-e2e-v1-16
    cluster: gke
    context: pull-cert-manager-e2e-v1-16
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.16 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.16"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-e2e-v1-17
    cluster: gke
    context: pull-cert-manager-e2e-v1-17
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.17 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.17"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-18
    cluster: gke
    context: pull-cert-manager-e2e-v1-18
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.18 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.18"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
  - name: pull-cert-manager-e2e-v1-19
    cluster: gke
    context: pull-cert-manager-e2e-v1-19
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.19 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.19"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
  - name: pull-cert-manager-e2e-v1-20
    cluster: gke
    context: pull-cert-manager-e2e-v1-20
    always_run: true
    optional: false
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.20"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
  # e2e test job with experimental certificates controller enabled
  - name: pull-cert-manager-experimental-e2e-v1-17
    cluster: gke
    context: pull-cert-manager-e2e-experimental-v1-17
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-1.2
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.17"
        # Enable the ExperimentalCertificateControllers feature gate
        - name: FEATURE_GATES
          value: "ExperimentalCertificateControllers=true"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
