presets:
- labels:
    preset-cloudflare-credentials: "true"
  env:
  - name: CLOUDFLARE_E2E_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: api-token
  - name: CLOUDFLARE_E2E_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: email
  - name: CLOUDFLARE_E2E_DOMAIN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: domain

- labels:
    preset-venafi-tpp-credentials: "true"
  env:
  - name: VENAFI_TPP_URL
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: url
  - name: VENAFI_TPP_ZONE
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: zone
  - name: VENAFI_TPP_USERNAME
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: username
  - name: VENAFI_TPP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: password

- labels:
    preset-venafi-cloud-credentials: "true"
  env:
  - name: VENAFI_CLOUD_ZONE
    valueFrom:
      secretKeyRef:
        name: venafi-cloud
        key: zone
  - name: VENAFI_CLOUD_APITOKEN
    valueFrom:
      secretKeyRef:
        name: venafi-cloud
        key: apitoken

- labels:
    preset-retry-flakey-tests: "true"
  env:
  - name: FLAKE_ATTEMPTS
    value: "2"

- labels:
    preset-aws-credentials: "true"
  env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws
        key: accesskey
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws
        key: secretkey
  - name: AWS_DEFAULT_REGION
    valueFrom:
      secretKeyRef:
        name: aws
        key: region

- labels:
    preset-disable-all-alpha-feature-gates: "true"
  env:
  - name: FEATURE_GATES
    value: "AllAlpha=false"

- labels:
    preset-disable-alpha-enable-output-formats-feature-gates: "true"
  env:
  - name: FEATURE_GATES
    value: "AllAlpha=false,AdditionalCertificateOutputFormats=true"

- labels:
    preset-enable-all-feature-gates: "true"
  env:
  - name: FEATURE_GATES
    value: "AllAlpha=true"

- labels:
    preset-enable-all-feature-gates-disable-ssa: "true"
  env:
  - name: FEATURE_GATES
    value: "AllAlpha=true,ServerSideApply=false"

- labels:
    preset-disable-all-alpha-beta-feature-gates: "true"
  env:
  - name: FEATURE_GATES
    value: "AllAlpha=false,AllBeta=false"

# Specific cert-manager e2e test suites can be skipped for all e2e tests here by
# setting GINKGO_SKIP value i.e 'Venafi Cloud|Gateway' will skip all Venafi
# Cloud and Gateway tests. Currently we skip all Venafi (VaaS and TPP) tests
# because they rely on external services being up and we don't want PRs and
# regular periodics to fail due to external service failures.
- labels:
    preset-ginkgo-skip-default: "true"
  env:
  - name: GINKGO_SKIP
    value: "Venafi"

- labels:
    preset-ginkgo-focus-http01-ingress: "true"
  env:
  - name: GINKGO_SKIP
    value: "Gateway"
  - name: GINKGO_FOCUS
    value: "Public ACME Server HTTP01 Issuer"

- labels:
    preset-ginkgo-focus-venafi: "true"
  env:
  - name: GINKGO_FOCUS
    value: 'Venafi'

- labels:
    preset-ginkgo-focus-venafi-tpp: "true"
  env:
  - name: GINKGO_FOCUS
    value: 'Venafi TPP'

- labels:
    preset-ginkgo-focus-venafi-cloud: "true"
  env:
  - name: GINKGO_FOCUS
    value: 'Venafi Cloud'

# This preset is used to enable the logic in the make-dind runner that manages
# a local cache and shares that cache with other jobs after successful completion.
# The runner script populates the LOCAL_CACHE_DIR location with a copy of the latest
# version of the shared cache. After the job succeeded, the shared cache is updated
# with the updated version of the local cache.
- labels:
    preset-local-cache: "true"
  env:
  - name: LOCAL_CACHE_ENABLED
    value: true
  - name: LOCAL_CACHE_DIR
    value: /home/prow/go/src/github.com/cert-manager/cert-manager/_bin/downloaded/
  - name: SHARED_CACHE_DIR
    value: /root/.prow_shared_cache/
  volumeMounts:
    - mountPath: /root/.prow_shared_cache/
      name: shared-cache
  volumes:
    - name: shared-cache
      hostPath:
        path: /tmp/shared_cache
        type: DirectoryOrCreate

- labels:
    preset-go-cache: "true"
  env:
  - name: GOCACHE
    value: /root/.prow_go_cache/
  - name: GOMODCACHE
    value: /root/.prow_go_mod_cache/
  volumeMounts:
    - mountPath: /root/.prow_go_cache/
      name: go-cache
    - mountPath: /root/.prow_go_mod_cache/
      name: go-mod-cache
  volumes:
    - name: go-cache
      hostPath:
        path: /tmp/go_cache
        type: DirectoryOrCreate
    - name: go-mod-cache
      hostPath:
        path: /tmp/go_mod_cache
        type: DirectoryOrCreate

# A preset which causes make e2e-setup to install cert-manager in accordance
# with https://cert-manager.io/docs/installation/best-practice/.
#
# See https://github.com/cert-manager/cert-manager/blob/7ab1461674149dc172b5fa9c3884064329c60af7/make/e2e-setup.mk#L163-L172
- labels:
    preset-bestpractice-install: "true"
  env:
  - name: E2E_SETUP_OPTION_BESTPRACTICE
    value: 'true'
