periodics:
- name: ci-trust-manager-bundle-updater
  max_concurrency: 1
  agent: kubernetes
  decorate: true
  annotations:
    description: Updates static bundle images for trust-manager
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    testgrid-create-job-group: "true"
    testgrid-dashboards: trust-manager-periodics
  labels:
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220830-c65cd19-4.2.1
      args:
      - runner
      - make
      - provision-buildx
      - ci-update-debian-bundle
      resources:
        requests:
          cpu: 2000m
          memory: 2Gi
      securityContext:
        # uses docker-in-docker
        privileged: true
    dnsConfig:
      options:
      - name: ndots
        value: "1"
  extra_refs:
  - org: cert-manager
    repo: trust
    base_ref: main
  interval: 2h
