presubmits:
  cert-manager/trust-manager:
  - name: pull-trust-manager-verify
    decorate: true
    always_run: true
    optional: false
    max_concurrency: 8
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20240416-5ccb4a8-1.22.1
        args:
        - runner
        - make
        - provision-buildx
        - verify
        resources:
          requests:
            cpu: 2000m
            memory: 1Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based trust-manager smoke job
  - name: pull-trust-manager-smoke
    always_run: true
    optional: false
    max_concurrency: 8
    decorate: true
    branches:
    - ^main$
    - ^release-.*$
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/golang-dind:20240416-5ccb4a8-1.22.1
        args:
        - runner
        - make
        - provision-buildx
        - smoke
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"
