presubmits:
  cert-manager/boilersuite:
  - name: pull-cert-manager-boilersuite-verify
    always_run: true
    max_concurrency: 2
    decorate: true
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20231115-6d9432b-1.21.3
        args:
        - runner
        - make
        - test-all
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
