apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: <redacted:non-trusted-server>
  name: default
- cluster:
    certificate-authority-data: <redacted>
    server: <redacted:trusted-server>
  name: trusted

users:
- name: default
  user:
    client-certificate-data: <redacted:client-cert-with-CN=client>
    client-key-data: <redacted>
- name: trusted
  user:
    client-certificate-data: <redacted:client-cert-with-CN=client>
    client-key-data: <redacted>

contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: trusted
    user: trusted
  name: trusted

current-context: default
